services:
  invoices-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5483:5432'
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: invoices
    # volumes:
    #   - ./docker:/docker-entrypoint-initdb.d
