services:
  pg-database:
    image: bitnami/postgresql:latest
    ports:
      - '5482:5432'
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: orders
    # volumes:
    #   - ./docker:/docker-entrypoint-initdb.d
